### ISSUE TITLE
Odd place to post but desperate times...

### ISSUE THREAD

**Issue by develroo** [MycroftAI/contributors#1]
Ok.. So for some reason I am unable to login to home.mycraoft.ai with my github account. It keeps on saying email address already in use. So I went to the slack for help but saw you have moved to mattermost. No problem tried to register for that but never got the email verification.

So is there a problem I should know about? Can't register Mycroft or check registrations. 

Thanks.

**Comment by aatchison** [comment]
This can happen if your email address is already in use. Could you try resetting your password with the same address you used for you github account?

**Comment by augustnmonteiro** [comment]
Heyo @develroo,

do you ever signed up using email or other social network on home.mycroft.ai?
can you try to reset the password? please

So what happens is that if you had signed using email before and never had connected with github we can't create a new user for you because the email already exists on our database.

**Comment by develroo** [comment]
Well therein like the problem. I did try to reset my home.mycroft.ai password. Only that email does not appear either. I can see no sign of it in spam folders or any other filters. 

The question remains though, if there is a sign in via Github button how can it overlap with a email login. And if it does how can either function if there is no reset email sent?

Please check the account record the email is the same as this github account and is the same email you are using to email me Newsetters the latest being 

```Message-ID: <20171026144810.18817.95153331.swift@mycroftai.activehosted.com>```

Subject: Mycroft Weekly Newsletter 10/26

Thanks.

**Comment by aatchison** [comment]
I can't find you in slack, are you on mattermost at chat.mycroft.ai?
If you wouldn't mind, send me the email address to arron.atchison@mycroft.ai and we'll have the guys look into your account.

**Comment by develroo** [comment]
ok sent. 

Thanks.

**Comment by matheuslima** [comment]
@develroo Arron passed me the email you sent him. Are you using the same email to try reset the password?

**Comment by develroo** [comment]
@matheuslima 

Yes. Same as the one I emailed aaron from. I left 2 messages on the #general    channel on Slack in the last 24 hours. 

Thanks.

**Comment by penrods** [comment]
Is this taken care of now?

**Comment by develroo** [comment]
Yes, it had to be manually resolved though. :)
